baseURL: https://greenblocks.network
# baseURL: https://greenblocks-site.firebaseapp.com/
# baseURL: http://localhost:1313
languageCode: en-us
title: GreenBlocks
theme: hugo-fresh-rn

params:
  hero:
    tagline: GreenBlocks
    subTagline: The future of small-scale agriculture is coming. Join the mailing list for more info.
    buttonText: Join the List
    image: illustrations/person.png
    bottomIcons:
    # - logos/clients/systek.svg
    # - logos/clients/tribe.svg
    # - logos/clients/kromo.svg
    # - logos/clients/infinite.svg
    # - logos/clients/gutwork.svg
  navbar:
    buttonText: Join the List
    logo:
      # src: logos/fresh.svg
      src: logos/greenblocks_logo_1.png
      alt: Main navbar logo
    # links:
    # - text: Features
    #   url: /
    # - text: Pricing
    #   url: /
    # - text: Dropdown
    #   dropdown: true
    #   links:
    #   - Dropdown item 1
    #   - Dropdown item 2
    #   - Dropdown item 3
  features:
    tagline: Cities are broken. Urban Farming can help.
    subTagline: GreenBlocks promotes urban farming by providing access to capital, secure land rights for landowners, and green investments for investors.
    panels:
    - title: Access To Capital
      image: illustrations/icons/mouse-globe.svg
      text: Secure crowdfunding on the blockchain unlocks the potential for farmers.
      button:
        text: Free Trial
        url: /
      delay: 1
    - title: Unused Urban Space
      image: illustrations/icons/laptop-cloud.svg
      text: GreenBlocks makes it easy and profitable to rent out unused urban space.
      button:
        text: Free Trial
        url: /
      delay: 2
    - title: Green Investments
      image: illustrations/icons/plug-cloud.svg
      text: GreenBlocks gives investors a way to support projects that help them and their cities.
      button:
        text: Free Trial
        url: /
      delay: 3
  sellingPoints:
    tagline: Here's our team.
    subtagline: We couldn't be more decentralized.
    points:
    - title: Billy Garrison
      location: Canada
      description: Blockchain Business Development
      icon: 1.png
    - title: Philipp Beer
      location: Germany
      description: Marketing + Business Development
      icon: philipp.jpg
    - title: Lewis Daly
      location: Australia
      description: Blockchain Development
      icon: lewisdaly.jpg
  platform:
    image: illustrations/mockups/app-mockup.png
    tagline: One Platform to rule them All
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    buttonText: Get Started
  clients:
    tagline: Our Clients love us!
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clientExamples:
    - name: Irma Walters
      position: Accountant
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 1.png
    - name: John Bradley
      position: Financial Analyst
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 2.png
    - name: Gary Blackman
      position: HR Manager
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 3.png
  contact:
    tagline: Drop us a line or two!
  footer:
    image: greenblocks_logo_light.png
    columns:
    - title: Contact
      links:
      - name: Email
        url: "mailto:lewis@vesselstech.com?subject=GreenBlocks"

    # - title: Docs
    #   links:
    #   - name: Get Started
    #     url: "#"
    #   - name: User guides
    #     url: "#"
    #   - name: Admin guide
    #     url: "#"
    #   - name: Developers
    #     url: "#"
    # - title: Blogroll
    #   links:
    #   - name: Latest News
    #     url: "#"
    #   - name: Tech articles
    #     url: "#"
    #   - name: Video Blog
    #     url: "#"
    # followUs:
    # - icon: mail
    #   url: "https://github.com/lucperkins"
    # - icon: dribbble
    #   url: "#"
    # - icon: facebook
    #   url: "#"
    # - icon: twitter
    #   url: "https://twitter.com/lucperkins"
    # - icon: bitbucket
    #   url: "#"

